baseURL       = "https://xsakix.github.io/ainews/"
languageCode  = "en-us"
title         = "Ainews"
theme         = "ananke"

publishDir    = "public"     # leave as-is if you deploy with gh-pages
canonifyURLs  = true

[params]
  description = "AI News by AI"
  author      = "Martin Seckar"

[outputs]            # guarantee HTML is emitted
  home   = ["HTML", "RSS"]
  section = ["HTML"]

[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
