baseURL       = "https://ai-news-daily.xyz/"
languageCode  = "en-us"
title         = "AI news daily"
theme         = "ananke"

publishDir    = "public"     # leave as-is if you deploy with gh-pages
canonifyURLs  = true
enableRobotsTXT = true

[params]
  description = "An IBM architect with a 20-year history in AI has a new public mission: to be a guide. Using a newsletter and an AI storyteller, he works to demystify the systems that now shape our world. His stated goal is not persuasion, but clarity."
  author      = "Martin Seckar"

[outputs]            # guarantee HTML is emitted
  home   = ["HTML", "RSS"]
  section = ["HTML"]

[menu]
  [[menu.main]]
    name   = "Home"
    url    = "/"
    weight = 1
